### ISSUE TITLE
Consider using O_TMPFILE

### ISSUE THREAD

**Issue by ajeetdsouza** [google/renameio#39]
`O_TMPFILE` is a Linux-specific flag that seems suited for _exactly_ the purpose of atomic file creation + renaming.

From the [manpage](https://man7.org/linux/man-pages/man2/open.2.html):

> There are two main use cases for O_TMPFILE:
> *  Improved tmpfile(3) functionality: race-free creation of temporary files that (1) are automatically deleted when closed; (2) can never be reached via any pathname; (3) are not subject to symlink attacks; and (4) do not require the caller to devise unique names.
> *  Creating a file that is initially invisible, which is then populated with data and adjusted to have appropriate filesystem attributes (fchown(2), fchmod(2), fsetxattr(2), etc.)  before being atomically linked into the filesystem in a fully formed state (using linkat(2) as described above).

**Comment by ajeetdsouza** [comment]
I just learned that there's no way to _replace_ an existing file using an `O_TMPFILE`. The only way to persist it is with `linkat`, which doesn't provide a way to overwrite the destination file (yet).

I'm closing this issue. Sorry for the spam!

**Comment by adam-azarchs** [comment]
That doesn't mean it isn't still useful.  You can use `O_TMPFILE` to create the file and then populate it, then link it under a temporary name, and rename it over the old file.  There _is_ still a window during which an unexpected program termination could leave the temp file lying around, but that window becomes much shorter - basically just the duration of a single `renameat` syscall opposed to at least 5[^1], some of which are potentially much slower.  There are also advantages API-wise in that the critical window is only for the duration of the call to `CloseAtomicallyReplace`; other code paths _should_ try to close the file descriptor but failure to do so will at least not result in unwanted temporary files being left lying around.

[^1]: `openat`, at least one `write`, possibly one or more of `fchmod`, `fchown`, `futimes`, `sync`, `close`, and still `renameat`

**Comment by adam-azarchs** [comment]
Also worth noting that there are many use cases where one wants to write a file atomically, so that other processes never see an incomplete view of the file, but where the destination file _doesn't_ already exist, so it doesn't need to _replace_ that destination, per se.  So the algorithm using this syscall would look something like
1. Open the directory file handle.
2. Create the anonymous file handle.
3. Write content to the file, set mode bits, etc.
4. Attempt to `linkat` to the destination location.  If that works, you're done, and there was never an opportunity for an unexpected process termination to leave garbage lying around.
5. Otherwise, `linkat` to a temporary name (and keep trying names until one works, same as how `CreateTemp` works) and then rename.  Then there _is_ still a window during which trash can be left lying around, or during which the temp file could theoretically be renamed by some other process, but it's much, much shorter - only between the `linkat` and the `renameat` calls, which happen back to back, as opposed to the entire time during which the temporary file is being written to, which could be a long time if it's a large file.
